name: Lint all Packages

on:
  pull_request:

jobs:
  lint-all-packages:
    name: Lint all Packages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint via better-scripts
        run: pnpm run scripts run lint