# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
#ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

name: Dockerfile Vuln Scanner

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker/**'
      - '**/docker/**'
      - 'Dockerfile.techdocs'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths:
      - 'docker/**'
      - '**/docker/**'
      - 'Dockerfile.techdocs'
  schedule:
   - cron: '17 1 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Set local docker image
        id: set-local-docker-image
        run: |
          echo "local_docker_image=trivy-scanner:$(date +%s)" >> $GITHUB_ENV
        
      - name: Build an image from Dockerfile
        # set DEVKJ-BOt PAT named PACKAGE_REGISTRY_GITHUB_TOKEN as a TRIVY_TOKEN variable
        # {{secrets.{NAME_YOU_SPECIFIED]}}
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg GITHUB_TOKEN=${{secrets.TRIVY_TOKEN}} --build-arg BUNDLE_GEMS__CONTRIBSYS__COM=${{secrets.TRIVY_TOKEN_2}} --build-arg RAILS_ENV=development --file docker/Dockerfile --tag ${{steps.set-local-docker-image.local_docker_image}} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.set-local-docker-image.local_docker_image }}
          format: 'sarif'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
